### ISSUE TITLE
Keypress on "enter" in firefox not behaves properly

### ISSUE THREAD

**Issue by avasuro** [fresheneesz/keysight#6]
If I press enter in firefox:

```javascript
input.on('keypress', function(e) {
    // In all browsers here will be '\n', but in firefox - '\u0000'
    var parsedKey = keysight(e).key; 
    if (parsedKey === '\n')
        alert('Works good');
    else
        alert('Works inpropertly, parsed key: ' + parsedKey);
});
```

**Comment by avasuro** [comment]
Created pull request with fix:
#5

**Comment by fresheneesz** [comment]
Thanks for the report! I'll try to get to reviewing your PR this weekend.

**Comment by fresheneesz** [comment]
So after looking at this, mapping \u0000 to enter isn't correct. Many keys end up as `event.charCode` \u0000, including enter, tab, backspace, pause, escape, pageup, etc etc. So your pull request wouldn't be accurate. If you want to detect something like enter, use the keydown or keyup events instead of keypress. In fact, it looks like keypress has been [deprecated entirely](https://developer.mozilla.org/en-US/docs/Web/Events/keypress).

**Comment by avasuro** [comment]
@fresheneesz 
Oh, you are right! Thanks for explanation and sorry for waste your time.

**Comment by fresheneesz** [comment]
No worries, thanks anyways!
